version: "3.9"

services:
    web1:
        container_name: esgi-docker-compose-web1
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        ports:
            - 8000:80
        restart: always
        depends_on:
            - db
        volumes:
            - ./web1/:/var/www/html/

    web2:
        container_name: esgi-docker-compose-web2
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        ports:
            - 8001:80
        restart: always
        depends_on:
            - db
        volumes:
            - ./web2/:/var/www/html/

    nginx1:
        container_name: esgi-docker-compose-nginx1
        build:
            context: .
            dockerfile: docker/nginx1/Dockerfile
        volumes:
            - ./web1:/usr/share/nginx/html
        ports:
            - "80:80"

    nginx2:
        container_name: esgi-docker-compose-nginx2
        build:
            context: .
            dockerfile: docker/nginx2/Dockerfile
        volumes:
            - ./web2:/usr/share/nginx/html
        ports:
            - "81:80"

    phpmyadmin:
        container_name: esgi-docker-compose-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8004:80"
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db

    db:
        container_name: esgi-docker-compose-db
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
