version: "3.9"

services:
    web1:
        container_name: esgi-docker-compose-web1
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        depends_on:
            - db

    web2:
        container_name: esgi-docker-compose-web2
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        depends_on:
            - db

    nginx1:
        container_name: esgi-docker-compose-nginx1
        build:
            context: .
            dockerfile: docker/nginx1/Dockerfile
        depends_on:
            - web1
        ports:
            - "3000:80"

    nginx2:
        container_name: esgi-docker-compose-nginx2
        build:
            context: .
            dockerfile: docker/nginx2/Dockerfile
        depends_on:
            - web2
        ports:
            - "8000:80"

    phpmyadmin:
        container_name: esgi-docker-compose-phpmyadmin
        depends_on:
            - db
        environment:
            PMA_HOST: db
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        restart: always

    db:
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root
        image: mysql
        restart: always
