version: "3.9"

services:
    web1:
        container_name: esgi-docker-compose-web1
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        depends_on:
            - db
        expose:
            - 9000
        volumes:
            - ./docker/web1:/var/www/html/public

    # web2:
    #     container_name: esgi-docker-compose-web2
    #     build:
    #         context: .
    #         dockerfile: docker/web/Dockerfile
    #     ports:
    #         - 8001:80
    #     restart: always
    #     depends_on:
    #         - db
    #     volumes:
    #         - ./docker/web2:/var/www/html

    nginx1:
        container_name: esgi-docker-compose-nginx1
        build:
            context: .
            dockerfile: docker/nginx1/Dockerfile
        volumes:
            - ./docker/web1:/var/www/html/public
        ports:
            - "8080:80"
        depends_on:
            - web1

    # nginx2:
    #     container_name: esgi-docker-compose-nginx2
    #     build:
    #         context: .
    #         dockerfile: docker/nginx2/Dockerfile
    #     volumes:
    #         - ./docker/web2:/usr/share/nginx/html
    #     ports:
    #         - "9001:80"

    phpmyadmin:
        container_name: esgi-docker-compose-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8004:80"
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db

    db:
        container_name: esgi-docker-compose-db
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
