version: "3.9"

services:
    web1:
        container_name: esgi-docker-compose-php
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        ports:
            - 8000:80
        restart: always
        depends_on:
            - db
        volumes:
            - ./web1/:/var/www/html/

    web2:
        container_name: esgi-docker-compose-node
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        ports:
            - 8001:80
        restart: always
        depends_on:
            - db
        volumes:
            - ./web2/:/var/www/html/

    nginx1:
        container_name: esgi-docker-compose-nginx1
        image: nginx
        volumes:
            - ./web1:/etc/nginx/templates
        ports:
            - "8002:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80

    nginx2:
        container_name: esgi-docker-compose-nginx2
        image: nginx
        volumes:
            - ./web2:/etc/nginx/templates
        ports:
            - "8003:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80

    phpmyadmin:
        container_name: esgi-docker-compose-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8004:80"
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db

    db:
        container_name: esgi-docker-compose-db
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
