# Dockerfile
FROM ubuntu

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR 

RUN composer Install \
    php artisan key:generate \
    php artisan migrate:fresh —seed
