# Dockerfile
FROM ubuntu

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

RUN apt-get update && apt-get install nodejs -y

WORKDIR /

RUN composer Install \
    php artisan key:generate \
    php artisan migrate:fresh —seed
