version: "3.9"

services:
    web1:
        build:
            context: ./web1/
            dockerfile: Dockerfile
        ports:
            - 8000:80
        restart: always
        depends_on:
            - db
        volumes:
            - ./web1/:/var/www/html/

    web2:
        image: php:8-apache
        ports:
            - 8001:80
        restart: always
        depends_on:
            - db
        volumes:
            - ./web2/:/var/www/html/

    nginx1:
        image: nginx
        volumes:
            - ./templates:/etc/nginx/templates
        ports:
            - "8002:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80

    nginx2:
        image: nginx
        volumes:
            - ./templates2:/etc/nginx/templates
        ports:
            - "8003:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8004:80"
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: "1"
        volumes:
            - mysql:/var/lib/mysql
volumes:
    mysql:
